openapi: 3.0.3
info:
  title: API Cadastro Politico
  description: "A Compass foi escolhida pelo Governo do Brasil para fazer uma API de cadastro de Partidos e Associados"

  version: 0.0.1
  contact:
    name: Suporte Dev
    email: lucas.peixoto.pb@compasso.com.br
  license:
    name: "Lincença: GPLv3"
    url: https://www.gnu.org/licenses/gpl-3.0.html
servers:
  - url: http://localhost:8080
    description: API Cadastro Politico
paths:
  /partidos:
    get:
      tags:
        - API Partido
      summary: Lista todos os Partidos
      description: "Através desse endpoint você poderá listar todos os Partidos. Existe filtros para o retorno da requisição, utilizando os Params. Ex: Filtrar por Ideologia - 'http://localhost:8080/partidos?Ideologia=e8squerda' (o valor da ideologia mesmo sendo um enum, pode ser colocado com letras minusculas). Ex: Ordenar por nome - 'http://localhost:8080/partidos?sort=nome,desc' (mudando desc para asc)."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PartidoId"

        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RespostaNotFoundParametro"

        5XX:
          description: "Erro no servidor, tente mais tarde!"

    post:
      summary: Cria um novo Partido
      description: "Através desse endpoint você poderá criar novos Partidos. Se algum campo obrigatório for violado, retornará 400 com uma mensagem informando o campo e o erro, se o parametrô estiver errado, retornará um 404"
      tags:
        - API Partido
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Partido"
      responses:
        201:
          description: "Created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PartidoId"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RespostaNotFoundParametro"
        400:
          description: Bad Request
          content:
            application/json:
              example: {
                "code": "BAD_REQUEST",
                "message": "Requisição Inválida",
                "details": [
                  "nome : não deve estar em branco"
                ]
              }
        5XX:
          description: "Erro no servidor, tente mais tarde!"

  /partidos/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
    get:
      summary: Lista os Partidos por id
      description: "Através desse endpoint você poderá consultar Partidos por id. Se não existir, retornará 404."
      tags:
        - API Partido
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PartidoId"
        400:
          description: Bad Request
          content:
            application/json:
              example: "http://localhost:8080/partidos/a"
        404:
          description: Not Found
          content:
            application/json:
              example: {
                "code": "PARTIDO_NAO_ENCONTRADO",
                "message": "Partido não encontrado",
                "details": [
                  "PARTIDO_NAO_ENCONTRADO"
                ]
              }
        5XX:
          description: "Erro no servidor, tente mais tarde!"

    put:
      summary: Autualiza Partido por id
      description: "Através desse endpoint você poderá atualizar um Partido. Se algum campo obrigatório for violado, retornará 400 com uma mensagem informando o campo e o erro, se o ID infromado não existir, retornará 404."
      tags:
        - API Partido
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Partido"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PartidoId"
        404:
          description: Partido não encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RespostaNotFoundAtualizar"
        400:
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RespostaBadRequestAtualizar"
        5XX:
          description: "Erro no servidor, tente mais tarde!"
    delete:
      summary: Excluir Partido por id
      description: "Através desse endpoint você poderá excluir um Partido. Se o ID infromado não existir, retornará 404."
      tags:
        - API Partido
      responses:
        204:
          description: "No Content"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RespostaNotFoundAtualizar"
        5XX:
          description: "Erro no servidor, tente mais tarde!"
components:
  schemas:
    Partido:
      type: object
      properties:
        nome:
          type: string
          example: União Brasil
        sigla:
          type: string
          example: UNIAO
        ideologia:
          type: string
          enum:
            - Direita
            - Esquerda
            - Centro
        fundacao:
          type: string
          example: 26-02-2002
    PartidoId:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome:
          type: string
          example: União Brasil
        sigla:
          type: string
          example: UNIAO
        ideologia:
          type: string
          enum:
            - Direita
            - Esquerda
            - Centro
        fundacao:
          type: string
          example: 26-02-2002
    RespostaNotFoundParametro:
      type: object
      properties:
        timestamp:
          type: string
          example: "2022-11-26T21:46:35.576+00:00"
        status:
          type: number
          example: 404
        error:
          type: string
          example: "Not Found"
        path:
          type: string
          example: "/partidoss"
    RespostaBadRequestAtualizar:
      type: object
      properties:
        code:
          type: string
          example: "BAD_REQUEST"
        message:
          type: string
          example: "Requisição Inválida"
        details:
          type: string
          example: "sigla : não deve estar em branco"
    RespostaNotFoundAtualizar:
      type: object
      properties:
        code:
          type: string
          example: "PARTIDO_NAO_ENCONTRADO"
        message:
          type: string
          example: "Partido não encontrado"
        details:
          type: string
          example: "PARTIDO_NAO_ENCONTRADO"