openapi: 3.0.3
info:
  title: API Cadastro Politico
  description: "A Compass foi escolhida pelo Governo do Brasil para fazer uma API de cadastro de Partys e associates"

  version: 0.0.1
  contact:
    name: Suporte Dev
    email: lucas.peixoto.pb@compasso.com.br
  license:
    name: "Lincença: GPLv3"
    url: https://www.gnu.org/licenses/gpl-3.0.html
servers:
  - url: http://localhost:8080
    description: API Cadastro Politico
paths:
  /Partys:
    get:
      tags:
        - Party
      summary: Lista todos os Partys
      description: "Através desse endpoint você poderá listar todos os Partys. Existe filtros para o retorno da requisição, utilizando os Params. Ex: Filtrar por Ideologia - 'http://localhost:8080/Partys?Ideologia=e8squerda' (o valor da ideologia mesmo sendo um enum, pode ser colocado com letras minusculas). Ex: Ordenar por nome - 'http://localhost:8080/Partys?sort=nome,desc' (mudando desc para asc)."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PartyId"

        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseNotFoundParametro"

        5XX:
          description: "Erro no servidor, tente mais tarde!"

    post:
      summary: Cria um novo Party
      description: "Através desse endpoint você poderá criar novos Partys. Se algum campo obrigatório for violado, retornará 400 com uma mensagem informando o campo e o erro, se o parametrô estiver errado, retornará um 404"
      tags:
        - Party
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Party"
      responses:
        201:
          description: "Created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PartyId"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseNotFoundParametro"
        400:
          description: Bad Request
          content:
            application/json:
              example: {
                "code": "BAD_REQUEST",
                "message": "Requisição Inválida",
                "details": [
                  "nome : não deve estar em branco"
                ]
              }
        5XX:
          description: "Erro no servidor, tente mais tarde!"
  /Partys/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
    get:
      summary: Lista os Partys por id
      description: "Através desse endpoint você poderá consultar Partys por id. Se não existir, retornará 404."
      tags:
        - Party
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PartysId"
        400:
          description: Bad Request
          content:
            application/json:
              example: "http://localhost:8080/Partys/a"
        404:
          description: Not Found
          content:
            application/json:
              example: {
                "code": "Party_NAO_ENCONTRADO",
                "message": "Party não encontrado",
                "details": [
                  "Party_NAO_ENCONTRADO"
                ]
              }
        5XX:
          description: "Erro no servidor, tente mais tarde!"
    put:
      summary: Autualiza Party por id
      description: "Através desse endpoint você poderá atualizar um Party. Se algum campo obrigatório for violado, retornará 400 com uma mensagem informando o campo e o erro, se o ID infromado não existir, retornará 404."
      tags:
        - Party
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Party"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PartyId"
        404:
          description: Party não encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseNotFoundAtualizar"
        400:
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseBadRequestAtualizar"
        5XX:
          description: "Erro no servidor, tente mais tarde!"
    delete:
      summary: Excluir Party por id
      description: "Através desse endpoint você poderá excluir um Party. Se o ID infromado não existir, retornará 404."
      tags:
        - Party
      responses:
        204:
          description: "No Content"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseNotFoundAtualizar"

        409:
          description: "Conflict"
          content:
            application/json:
              example: {
                "code": "ENTIDADE_EM_USO",
                "message": "Entidade em uso",
                "details": [
                  "Party de código 4 não pode ser removido, pois está em uso"
                ]
              }
        5XX:
          description: "Erro no servidor, tente mais tarde!"
  /Partys/{id}/associates:
    parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
    get:
      summary: Lista todos associates do Party
      description: "Através desse endpoint você poderá listar todos os associates de um Party escolhido. EX: http://localhost:8080/Partys/2/associates"
      tags:
        - Party
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/associatesSoComId"
        400:
          description: Bad Request
          content:
            application/json:
              example: "http://localhost:8080/Partys/a"
        404:
          description: Not Found
          content:
            application/json:
              example: {
                "code": "Party_NAO_ENCONTRADO",
                "message": "Party não encontrado",
                "details": [
                  "Party_NAO_ENCONTRADO"
                ]
              }
        5XX:
          description: "Erro no servidor, tente mais tarde!"
  /associates:
    get:
      tags:
        - associate
      summary: Lista todos os associates
      description: "Através desse endpoint você poderá listar todos os associates. Existe filtros para o retorno da requisição, utilizando os Params. Ex: Filtrar por Cargo - 'http://localhost:8080/associates?Cargo=Prefeito' (o valor da cargo mesmo sendo um enum, pode ser colocado com letras minusculas). Ex: Ordenar por nome - 'http://localhost:8080/associates?sort=nome,desc' (mudando desc para asc)."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/associateCompleto"

        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseNotFoundParametroassociates"

        5XX:
          description: "Erro no servidor, tente mais tarde!"
    post:
      summary: Cria um novo associate
      description: "Através desse endpoint você poderá criar novos associates. Se algum campo obrigatório for violado, retornará 400 com uma mensagem informando o campo e o erro, se o parametrô estiver errado, retornará um 404"
      tags:
        - associate
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Party"
      responses:
        204:
          description: "No Content"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/associatesCompletoSemParty"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseNotFoundParametroassociates"
        400:
          description: Bad Request
          content:
            application/json:
              example: {
                "code": "BAD_REQUEST",
                "message": "Requisição Inválida",
                "details": [
                  "nome : não deve estar em branco"
                ]
              }
        5XX:
          description: "Erro no servidor, tente mais tarde!"
  /associates/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
    get:
      summary: Lista todos associates
      description: "Através desse endpoint você poderá listar todos os associates. EX: http://localhost:8080/associates"
      tags:
        - associate
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/associatesCompleto"
        400:
          description: Bad Request
          content:
            application/json:
              example: "http://localhost:8080/associates/a"
        404:
          description: Not Found
          content:
            application/json:
              example: {
                "code": "associate_NAO_ENCONTRADO",
                "message": "associate não encontrado",
                "details": [
                  "associate_NAO_ENCONTRADO"
                ]
              }
        5XX:
          description: "Erro no servidor, tente mais tarde!"
    put:
      summary: Autualiza associate por id
      description: "Através desse endpoint você poderá atualizar um associate. Se algum campo obrigatório for violado, retornará 400 com uma mensagem informando o campo e o erro, se o ID infromado não existir, retornará 404."
      tags:
        - associate
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/associateSemId"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/associateCompleto"
        404:
          description: Party não encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseNotFoundParametroassociates"
        400:
          description: "Bad Request"
          content:
            application/json:
              example: {
                "code": "BAD_REQUEST",
                "message": "Requisição Inválida",
                "details": [
                  "nome : não deve estar em branco"
                ]
              }
        5XX:
          description: "Erro no servidor, tente mais tarde!"
    delete:
      summary: Excluir associate por id
      description: "Através desse endpoint você poderá excluir um associate. Se o ID infromado não existir, retornará 404."
      tags:
        - associate
      responses:
        204:
          description: "No Content"
        400:
          description: Bad Request
          content:
            application/json:
              example: "http://localhost:8080/associates/a"
        404:
          description: Not Found
          content:
            application/json:
              example: {
                "code": "associate_NAO_ENCONTRADO",
                "message": "associate não encontrado",
                "details": [
                  "associate_NAO_ENCONTRADO"
                ]
              }
        5XX:
          description: "Erro no servidor, tente mais tarde!"
  /associates/desvincular/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
    put:
      summary: Desvincula associate do Party
      description: "Através desse endpoint você poderá desvincular um associate. O id passado é do associate"
      tags:
        - associate
      responses:
        204:
          description: "No Content"
        404:
          description: associate não encontrado
          content:
            application/json:
              example:
                {
                  "code": "associate_NAO_ENCONTRADO",
                  "message": "associate não encontrado",
                  "details": [
                    "associate_NAO_ENCONTRADO"
                  ]
                }
  /associates/Partys:
    post:
      summary: Vincular associate a um Party
      description: "Através desse endpoint você poderá vincular associates. Se algum campo obrigatório for violado, retornará 400 com uma mensagem informando o campo e o erro, se o parametrô estiver errado, retornará um 404"
      tags:
        - associate
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Associacao"
      responses:
        204:
          description: "No Content"

        404:
          description: Not Found
          content:
            application/json:
              example: {
                "code": "associate_NAO_ENCONTRADO",
                "message": "associate não encontrado",
                "details": [
                  "associate_NAO_ENCONTRADO"
                ]
              }
        5XX:
          description: "Erro no servidor, tente mais tarde!"
components:
  schemas:
    Party:
      type: object
      properties:
        nome:
          type: string
          example: União Brasil
        sigla:
          type: string
          example: UNIAO
        ideologia:
          type: string
          enum:
            - Direita
            - Esquerda
            - Centro
        fundacao:
          type: string
          example: 26-02-2002
    PartyId:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome:
          type: string
          example: União Brasil
        sigla:
          type: string
          example: UNIAO
        ideologia:
          type: string
          enum:
            - Direita
            - Esquerda
            - Centro
        fundacao:
          type: string
          example: 26-02-2002
    PartysId:
      type: array
      items:
        $ref: "#/components/schemas/PartyId"
    associateSemId:
      type: object
      properties:
        nome:
          type: string
          example: Lucas Magno
        cargo:
          type: string
          enum:
            - Nenhum
            - Vereador
            - Prefeito
            - Deputado Estadual
            - Deputado Federal
            - Senador
            - Governador
            - Presidente
        sexo:
          type: string
          enum:
            - MASCULINO
            - FEMININO
        nascimento:
          type: string
          example: 26-02-2002
    associateSoComId:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome:
          type: string
          example: Lucas Magno
        cargo:
          type: string
          enum:
            - Nenhum
            - Vereador
            - Prefeito
            - Deputado Estadual
            - Deputado Federal
            - Senador
            - Governador
            - Presidente
        sexo:
          type: string
          enum:
            - MASCULINO
            - FEMININO
        nascimento:
          type: string
          example: 26-02-2002
    associatesSoComId:
      type: array
      items:
        $ref: "#/components/schemas/associateSoComId"
    associateCompleto:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome:
          type: string
          example: Lucas Magno
        cargo:
          type: string
          enum:
            - Nenhum
            - Vereador
            - Prefeito
            - Deputado Estadual
            - Deputado Federal
            - Senador
            - Governador
            - Presidente
        sexo:
          type: string
          enum:
            - MASCULINO
            - FEMININO
        nascimento:
          type: string
          example: 26-02-2002
        Party:
          type: object
          properties:
            id:
              type: integer
              example: 1
            nome:
              type: string
              example: União Brasil
            sigla:
              type: string
              example: UNIAO
            ideologia:
              type: string
              enum:
                - Direita
                - Esquerda
                - Centro
            fundacao:
              type: string
              example: 26-02-2002
    associatesCompleto:
      type: array
      items:
        $ref: "#/components/schemas/associateCompleto"
    associatesCompletoSemParty:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome:
          type: string
          example: Lucas Magno
        cargo:
          type: string
          enum:
            - Nenhum
            - Vereador
            - Prefeito
            - Deputado Estadual
            - Deputado Federal
            - Senador
            - Governador
            - Presidente
        sexo:
          type: string
          enum:
            - MASCULINO
            - FEMININO
        nascimento:
          type: string
          example: 26-02-2002
        Party:
          type: string
          example:
    Associacao:
      type: object
      properties:
        associateId:
          type: integer
          example: 6
        PartyId:
          type: integer
          example: 7
    responseBadRequestAtualizar:
      type: object
      properties:
        code:
          type: string
          example: "BAD_REQUEST"
        message:
          type: string
          example: "Requisição Inválida"
        details:
          type: string
          example: "sigla : não deve estar em branco"
    responseNotFoundParametro:
      type: object
      properties:
        timestamp:
          type: string
          example: "2022-11-26T21:46:35.576+00:00"
        status:
          type: number
          example: 404
        error:
          type: string
          example: "Not Found"
        path:
          type: string
          example: "/Partyss"
    responseNotFoundParametroassociates:
      type: object
      properties:
        timestamp:
          type: string
          example: "2022-11-26T21:46:35.576+00:00"
        status:
          type: number
          example: 404
        error:
          type: string
          example: "Not Found"
        path:
          type: string
          example: "/associatess"
    responseNotFoundAtualizar:
      type: object
      properties:
        code:
          type: string
          example: "Party_NAO_ENCONTRADO"
        message:
          type: string
          example: "Party não encontrado"
        details:
          type: string
          example: "Party_NAO_ENCONTRADO"