logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
spring:
  datasource:
    url: jdbc:sqlserver://states.database.windows.net:1433;database=db-states;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: adm-user
    password: Lucas123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect
        ddl-auto: create-drop