CREATE TABLE ASSOCIADO(
    ID BIGINT AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    CARGO VARCHAR(40) NOT NULL,
    SEXO VARCHAR(15) NOT NULL,
    NASCIMENTO DATETIME NULL,
--    PARTIDO_SIGLA VARCHAR(6) NOT NULL,
    PRIMARY KEY (ID)
)engine=InnoDB;

CREATE TABLE PARTIDO(
    ID BIGINT AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    SIGLA VARCHAR(6) NOT NULL,
    IDEOLOGIA VARCHAR(10) NOT NULL,
    FUNDACAO DATETIME NULL,
    PRIMARY KEY (ID)
)engine=InnoDB;