INSERT INTO PARTIDO (NOME, SIGLA, IDEOLOGIA, FUNDACAO) VALUES ('Partido da Social Democracia Brasileira', 'PSDB', 'CENTRO', '1988-06-25');
INSERT INTO PARTIDO (NOME, SIGLA, IDEOLOGIA, FUNDACAO) VALUES ('Progressistas', 'PP', 'DIREITA', '1995-05-14');
INSERT INTO PARTIDO (NOME, SIGLA, IDEOLOGIA, FUNDACAO) VALUES ('Partido Liberal', 'PL', 'DIREITA', '2006-10-26');
INSERT INTO PARTIDO (NOME, SIGLA, IDEOLOGIA, FUNDACAO) VALUES ('Novo', 'NOVO', 'DIREITA', '2011-02-12');
INSERT INTO PARTIDO (NOME, SIGLA, IDEOLOGIA, FUNDACAO) VALUES ('Partido dos Trabalhadores', 'PT', 'ESQUERDA', '1980-02-10');

INSERT INTO ASSOCIADO (NOME, CARGO, SEXO, NASCIMENTO) VALUES ('RUI COSTA', 'GOVERNADOR', 'MASCULINO', '1945-10-27');
INSERT INTO ASSOCIADO (NOME, CARGO, SEXO, NASCIMENTO) VALUES ('ANDRÉ MERLO', 'PREFEITO', 'MASCULINO', '1965-11-25');
INSERT INTO ASSOCIADO (NOME, CARGO, SEXO, NASCIMENTO) VALUES ('Zé Cocá', 'DEPUTADO_ESTADUAL', 'MASCULINO', '1976-5-24');
INSERT INTO ASSOCIADO (NOME, CARGO, SEXO, NASCIMENTO) VALUES ('Thai Spinello', 'VEREADOR', 'FEMININO', '1989-07-12');
INSERT INTO ASSOCIADO (NOME, CARGO, SEXO, NASCIMENTO) VALUES ('Beatriz Kicis Torrents de Sordi', 'DEPUTADO_FEDERAL', 'FEMININO', '1961-09-19');
