CREATE TABLE PARTIDO(
    ID BIGINT AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    SIGLA VARCHAR(10) NOT NULL,
    IDEOLOGIA VARCHAR(10) NOT NULL,
    FUNDACAO DATETIME NULL,
    PRIMARY KEY (ID)
)engine=InnoDB;