CREATE TABLE PARTY(
    ID BIGINT AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    ACRONYM VARCHAR(10) NOT NULL,
    IDEOLOGY VARCHAR(10) NOT NULL,
    FOUNDATION DATETIME NULL,
    PRIMARY KEY (ID)
)engine=InnoDB;