CREATE TABLE ASSOCIATE(
    ID BIGINT AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    OFFICE VARCHAR(40) NOT NULL,
    SEX VARCHAR(15) NOT NULL,
    BIRTH DATETIME NULL,
    PARTY_ID BIGINT,
    FOREIGN KEY (PARTY_ID) REFERENCES PARTY(ID),
    PRIMARY KEY (ID)
)engine=InnoDB;