CREATE TABLE ASSOCIATE(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    OFFICE VARCHAR(40) NOT NULL,
    SEX VARCHAR(15) NOT NULL,
    BIRTH DATETIME NULL,
    PARTY_ID INT FOREIGN KEY REFERENCES PARTY(ID)
);