INSERT INTO PARTY (NAME, ACRONYM, IDEOLOGY, FOUNDATION) VALUES ('Party da Social Democracia Brasileira', 'PSDB', 'CENTER', '1988-06-25');
INSERT INTO PARTY (NAME, ACRONYM, IDEOLOGY, FOUNDATION) VALUES ('Progressistas', 'PP', 'RIGHT', '1995-05-14');
INSERT INTO PARTY (NAME, ACRONYM, IDEOLOGY, FOUNDATION) VALUES ('Party Liberal', 'PL', 'RIGHT', '2006-10-26');
INSERT INTO PARTY (NAME, ACRONYM, IDEOLOGY, FOUNDATION) VALUES ('Novo', 'NOVO', 'RIGHT', '2011-02-12');
INSERT INTO PARTY (NAME, ACRONYM, IDEOLOGY, FOUNDATION) VALUES ('Party dos Trabalhadores', 'PT', 'LEFT', '1980-02-10');

INSERT INTO ASSOCIATE (NAME, OFFICE, SEX, BIRTH, PARTY_ID) VALUES ('RUI COSTA', 'GOVERNOR', 'MALE', '1945-10-27', 5);
INSERT INTO ASSOCIATE (NAME, OFFICE, SEX, BIRTH, PARTY_ID) VALUES ('ANDRÉ MERLO', 'MAYOR', 'MALE', '1965-11-25', 1);
INSERT INTO ASSOCIATE (NAME, OFFICE, SEX, BIRTH, PARTY_ID) VALUES ('Zé Cocá', 'STATE_DEPUTY', 'MALE', '1976-5-24', 2);
INSERT INTO ASSOCIATE (NAME, OFFICE, SEX, BIRTH, PARTY_ID) VALUES ('Thai Spinello', 'ALDERMAN', 'FEMALE', '1989-07-12', 4);
INSERT INTO ASSOCIATE (NAME, OFFICE, SEX, BIRTH, PARTY_ID) VALUES ('Beatriz Kicis Torrents de Sordi', 'FEDERAL_DEPUTY', 'FEMALE', '1961-09-19', 3);